---
title: "Homework 5"
author: "Caroline Kern-Allely"
date: "2024-11-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

As always, I'll load my libraries first.
```{r libraries, message = FALSE}
library("tidyverse")
library("readr")
library("lubridate")
library("purrr")
library("forcats")
library("stringr")
library("ggplot2")
library("scales")
library("broom")
library("ggfortify")
library("stringr")
library("ggthemes")
```

First, I'll load and clean the homicides data.
```{r data, message = FALSE}
homicides <- read_csv("data/homicide-data.csv")

homicides <- homicides %>%
  mutate(city_name = paste(city, state, sep = ", "))
```

Organize and tidy baltimore data.
```{r baltimore}
baltimore <- homicides %>%
  filter(city_name == "Baltimore, MD") %>%
  mutate(reported_date = as.Date(as.character(reported_date), format = "%Y%m%d"),
         day = day(reported_date),
         month = month(reported_date),
         year = year(reported_date)) %>%
  group_by(year, month) %>%
  summarize(total_homicides = n()) %>%
  mutate(month_year = as.Date(paste(year, month, "01", sep = "-"))) %>%
    mutate(season = case_when(
    month >= 5 & month <= 10 ~ "Summer",
    month >= 1 & month <=4 | month %in% 11:12 ~ "Winter"))
```
Next, I'll work on recreating the graph from the coursebook.
```{r graph, fig.height = 3, fig.width = 10}
plot <- baltimore %>%
  ggplot(aes(x = month_year, y = total_homicides)) +
  geom_bar(aes(fill = season), 
           stat = "identity", 
           position = "dodge") +
  geom_smooth(method = "loess", 
              span = 0.1,
              color = "royalblue",
              #alpha = 0.7,
              se = FALSE,
              show.legend = FALSE) +
  geom_vline(xintercept = as.Date("2015-04-12"), 
             color = "red", 
             linetype = "dashed", 
             linewidth = 1) +
  geom_text(aes(x = as.Date("2015-04-12"), y = 40),
            label = "Arrest of \n Freddie Gray",
            color = "lightgray",
            size = 4,
            hjust = 1.1,
            vjust = 0.5) +
  labs(title = "Homicides in Baltimore, MD",
       x = "Date",
       y = "Monthly Homicides") +
  scale_fill_manual(values = c("Summer" = "lightgray", 
                               "Winter" = "lightblue")) +
  theme_dark() +
  theme(legend.position = "bottom",
        legend.title = element_blank())

print(plot)
```